@startuml
!theme cerulean
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

top to bottom direction

Person(client, "Клиент")
Person(bo_manager, "Менеджер бэк-офиса")

System(website, "Сайт", "PHP и React.js")
System(internet_back, "Интернет-банк", "ASP.NET MVC 4.5 на основе .NET Framework 4.5 и СУБД MS SQL")
System(abs, "АБС", "Delphi, Oracle.")

System(conveyor, "Кредитный конвейер", "Camunda BPM")
System(scoring, "Скоринговая система", "Python (Flask), PostgreSQL")

System_Ext(bks, "Бюро кредитных историй")
System_Ext(sms_gate, "СМС-шлюз")

Rel(client, website, "Просмотр кредитных предложений, подача заявки")
Rel(client, internet_back, "Просмотр кредитных предложений, подача заявки")

Rel(bo_manager, abs, "Получение заявок на кредит")
Rel(bo_manager, conveyor, "Обработка заявок на кредит")

Rel(website, bks, "Получение общих данных бюро кредитных историй")
Rel(website, abs, "Предача заявок на колучение кредита в АБС")
Rel(internet_back, abs, "Предача заявок на колучение кредита в АБС")

Rel(abs, conveyor, "Передача заявок на кредит")
Rel(conveyor, abs, "Передача решений по заявкам")

Rel(conveyor, scoring, "Определение рейтинга клиента")
Rel(conveyor, bks, "Кредитная исторая клиента")

Rel(abs, sms_gate, "Подтверждение операции")
Rel(sms_gate, client, "Подтверждение операции")

@enduml